application: bookwith-biz
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always
  
- url: /ipn
  script: handlers/ipn.php
  secure: always
  
- url: /assets 
  static_dir: assets
  secure: always
  
- url: /.*
  script: main.php
  secure: optional
